config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :posts do
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do
    resources :comments
  end
  root to: 'posts#home'


  mount ActionCable.server => '/cable'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :content, presence: true, length: { minimum: 2, maximum: 1000 }

  after_create_commit { CommentBroadcastJob.perform_later(self) }

end

app/models/guest_user.rb
class GuestUser < User
  attr_accessor :email, :id
end

app/models/post.rb
class Post < ApplicationRecord

  validates_presence_of :title, :body

  belongs_to :user, optional: true
  acts_as_votable
  has_many :comments, dependent: :destroy

  after_initialize :set_defaults

  def set_defaults
    self.images ||= "http://placehold.it/350x200"
  end
end

app/models/topic.rb
class Topic < ApplicationRecord
	validates_presence_of :title

	has_many :posts
end

app/models/user.rb
    class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  acts_as_voter
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comments, dependent: :destroy

  def set_defaults
    self.profile_image ||= "http://placehold.it/350x200"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = current_user.comments.build(comment_params)
    # redirect_back
  end




  # def create
  #   @post = Post.find(params[:post_id])
  #   @comment = @post.comments.build(comment_params)
  #   @comment.quother = true if signed_in?
  #   if @comment.save
  #     @new_comment = @post.comments.new
  #     respond_to do |format|
  #       format.html do
  #         flash[:success] = 'Your comment has been posted.'
  #         redirect_to @post
  #       end
  #       format.js
  #     end
  #   else
  #     @new_comment = @comment
  #     respond_to do |format|
  #       format.html { render @post }
  #       format.js { render action: 'failed_save' }
  #     end
  #   end
  # end


  private


  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    @posts = Post.all(params[:page]).per(5)
  end
	
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote]

  # GET /posts
  # GET /posts.json
  def home
   @posts = Post.page(params[:page]).per(5)
   @featured_posts = get_featured_posts
  end

  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.includes(:comments).find(params[:id])
    @comment = Comment.new
    @seo_keywords = @post.body
  end

  # def show
  #   @post = Post.find(params[:id])
  #   @comments = @post.comments
  #   @new_comment = @post.comments.new
  #   @seo_keywords = @post.body
  # end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

def upvote
 @post.upvote_from current_user
 redirect_to posts_path
end

def downvote
 @post.downvote_from current_user
 redirect_to posts_path
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:ranking, :topic, :body, :title, :images)
    end

    def get_featured_posts
      Post.all.to_a.sort_by {|post| post.get_upvotes.size}.last(3)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
	class CodeRayify < Redcarpet::Render::HTML
    def block_code(code, language)
      CodeRay.scan(code, language || :ruby).div
    end
  end

  def markdown(text)
    coderayified = CodeRayify.new(filter_html: true, hard_wrap: true)

    options = {
      fenced_code_blocks: true,
      no_intra_emphasis: true,
      autolink: true,
      lax_html_blocks: true,
    }

    markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
    markdown_to_html.render(text).html_safe
  end
end

app/views/comments/_comment.html.erb
<div class="comment-card">
  <div class="card">
    <div class="card-block">
      <div class="row">
        <div class="col-md-2">
          
        </div>

        <div class="col-md-10">
          <div>
            <%= markdown comment.content %>
          </div>

          <div class="comment-attribution">
            Comment posted <%= distance_of_time_in_words(comment.created_at, Time.now) %> ago
          </div>
          
        </div>
      </div>
    </div>
  </div>
</div>

app/views/comments/_comment_form.html.erb
<div class='form-group'>
  <%= form_for @comment, url: '#' do |f| %>
    
    
    <%= f.text_area :content, id: :comment_content, class: 'form-control', rows: 7, placeholder: '```language
      Your Code Here
  ``` 
  (Feel free to use markdown for code snippets.  Default language set to Ruby)' %>
  
    <%= f.submit 'Post Comment', class: 'btn btn-primary' %>
   
  <% end %>
</div>

app/views/comments/create.js.erb
var comments_list = $('#comments-list');
comments_list.append('<%= escape_javascript(render partial: @comment) %>');
comments_list.find('div:last-child').addClass('last-comment');
$('#comments-count').html('This article has <%= escape_javascript(pluralize(@post.comments.count, 'comment')) %>');
$('#comment-form').html('<%= escape_javascript(render('comments/comment_form')) %>');

app/views/comments/destroy.js.erb
$('#comments-list').html('<%= escape_javascript(render partial: @post.comments) %>');
$('#comments-count').html('This article has <%= escape_javascript(pluralize(@post.comments.count, 'comment')) %>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlumniApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<header>
      <%= render "shared/nav" %>
    </header>

    <%= yield %>
  </body>
</html>

app/views/posts/_alumni_feature.html.erb
<div  id="alumni-feature">

  <h2 id="feature-header">
    Alumni Feature
  </h2>
    
  <%= image_tag 'http://adigaskell.org/wp-content/uploads/2016/01/math-and-coding.jpg', id:"feature-image" %>

  <p id="feature-text">
    We thought that this alumnus was way cool because they were actually able to find a job and make money.
  </p>
</div>

app/views/posts/_carousel.html.erb
<link href="carousel.css" rel="stylesheet">
    </head>
    <body>
      <main role="main">

        <div id="myCarousel" class="carousel slide" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img class="first-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="First slide">
              <div class="container">
                <div class="carousel-caption text-left">
                  <h1><%= @featured_posts.first.title %></h1>
                  <p><%= @featured_posts.first.body %></p>
                  <p><%= link_to 'View', @featured_posts.first, class: 'btn btn-primary btn-large' %></p>
                </div>
              </div>
            </div>
            <div class="carousel-item">
              <img class="second-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Second slide">
              <div class="container">
                <div class="carousel-caption">
                  <h1><%= @featured_posts.second.title %></h1>
                  <p><%= @featured_posts.second.body %></p>
                  <p><%= link_to 'View', @featured_posts.second, class: 'btn btn-primary btn-large' %></p>
                </div>
              </div>
            </div>
            <div class="carousel-item">
              <img class="third-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Third slide">
              <div class="container">
                <div class="carousel-caption text-right">
                  <h1><%= @featured_posts.third.title %></h1>
                  <p><%= @featured_posts.third.body %></p>
                  <p><%= link_to 'View', @featured_posts.third, class: 'btn btn-primary btn-large' %></p>
                </div>
              </div>
            </div>
          </div>
          <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :title, id: :post_title, class: 'form-control', placeholder: 'Post Title' %>
  </div>

  <div class="form-group">
    <%= form.select :topic, [['Front End Resources','front end resources'],['Back End Resources','back end resources'],['Misc Resources','mis resources'],['Ruby Resources','ruby resources'],['Rails Resources','rails resources'],['Job Resources','job resources'],['Job Postings','job posting']]%>
  </div>

  <div class="form-group">
    <%= form.text_area :body, id: :post_body, class: 'form-control', rows: 7, placeholder: '```language
Your Code Here
``` 
(Feel free to use markdown for code snippets  Default language set to Ruby)' %>
  </div>

  <div class="form-group">
    <%= form.text_area :images, id: :post_images, class: 'form-control', placeholder: 'image upload' %>
  </div>

  <div class="form-group">
    <%= form.submit "Submit", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="container">
	<h1>Editing Post</h1>

	<%= render 'form', post: @post %>

	<%= link_to 'Show', @post %> |
	<%= link_to 'Back', posts_path %>
</div>

app/views/posts/home.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>Carousel Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="../../../../dist/css/bootstrap.min.css" rel="stylesheet">
<div class="container-fluid" id='homepage-carousel-container'>
    <!-- Custom styles for this template -->
  <div class= "col-md-9">
      <link href="carousel.css" rel="stylesheet">
    </head>
    <body>
      <main role="main">

        <div id="myCarousel" class="carousel slide" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner">
            <div class="carousel-item active">
              <img class="first-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="First slide">
              <div class="container">
                <div class="carousel-caption text-left">
                  <h1><%= @featured_posts.first.title %></h1>
                  <p><%= @featured_posts.first.body %></p>
                  <p><%= link_to 'View', @featured_posts.first, class: 'btn btn-primary btn-large' %></p>
                </div>
              </div>
            </div>
            <div class="carousel-item">
              <img class="second-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Second slide">
              <div class="container">
                <div class="carousel-caption">
                  <h1><%= @featured_posts.second.title %></h1>
                  <p><%= @featured_posts.second.body %></p>
                  <p><%= link_to 'View', @featured_posts.second, class: 'btn btn-primary btn-large' %></p>
                </div>
              </div>
            </div>
            <div class="carousel-item">
              <img class="third-slide" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Third slide">
              <div class="container">
                <div class="carousel-caption text-right">
                  <h1><%= @featured_posts.third.title %></h1>
                  <p><%= @featured_posts.third.body %></p>
                  <p><%= link_to 'View', @featured_posts.third, class: 'btn btn-primary btn-large' %></p>
                </div>
              </div>
            </div>
          </div>
          <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
      <div class="col-md-3">
        <%= render 'alumni_feature' %>
      </div>
</div>
<div class="container">    
  <button type="button" class="btn btn-primary">All</button>
   
  <button type="button" class="btn btn-primary">New</button>

  <button type="button" class="btn btn-primary">Top</button>
      
  <button type="button" class="btn btn-primary">Oldest</button>
</div>

        <!-- START THE FEATURETTES -->


        <hr class="featurette-divider">
            <div class="row featurette ">

              <% @posts.each do |post| %>
              <div class="container ">  
                <div class="col-md-8">
                  <h2>Post Title</h2>
                  <p class="lead"><%= post.body %></p>
                </div>
                <div class="col-md-4">
                  <img class="featurette-image img-fluid mx-auto" src="http://via.placeholder.com/150x150" alt="Generic placeholder image">
                </div>
              <hr>
              </div>
              <% end %>

            </div>

              <span class="paginate-render"><%= paginate @posts %><span>

        <hr class="featurette-divider">



        <!-- /END THE FEATURETTES -->


      </div><!-- /.container -->


      <!-- FOOTER -->
      <footer class="container">
        <p class="float-right"><a href="#">Back to top</a></p>
        <p>&copy; 2018 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
      </footer>


    </main>

</span>

    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="../../../../assets/js/vendor/popper.min.js"></script>
    <script src="../../../../dist/js/bootstrap.min.js"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="../../../../assets/js/vendor/holder.min.js"></script>
  </body>
</html>

app/views/posts/index.html.erb
<div class="container">

  <p id="notice"><%= notice %></p>


  <table>
    <thead>
      <tr>
        <th>Upvotes</th>  
        <th>Downvotes</th>
        <th>Topic</th>
        <th>Body</th>
        <th>Images</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td>  
          <%=link_to like_post_path(post), method: :put, class: 'btn btn-default btn-sm' do %>   <span class="glyphicon glyphicon-chevron-up"></span>
           like <%=post.get_upvotes.size%>
            <% end %>
        </td>
        <td> 
          <%=link_to dislike_post_path(post), method: :put, class: 'btn btn-default btn-sm' do %>
           <span class="glyphicon glyphicon-chevron-down"></span>
           dislike <%=post.get_downvotes.size%></td>
          <%end%>
        </td>
          <td><%= post.topic %></td>
          <td><%= post.body %></td>
          <td><%= post.images %></td>
          <td><%= link_to 'Show', post %></td>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
          <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Post', new_post_path %>
</div>

app/views/posts/new.html.erb
<div class="container">
	<h1>New Post</h1>

	<%= render 'form', post: @post %>

	<%= link_to 'Back', posts_path %>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="card">
    <p id="notice"><%= notice %></p>

    <p>
      <h4>Ranking: <%= @post.ranking %></h4>
    </p>

    <h4>Topic:</h4>
    <p>
      <%= @post.topic %>
    </p>

    <h4>Post:</h4>
    <p>
      <%= markdown @post.body %>
    </p>

    <p>
      <%= @post.images %>
    </p>
  </div>
</div>


<div class="container">
  <h4>Comments:</h4>
  <div id="comment-form">
    <%= render 'comments/comment_form' %>
  </div>

  <div id="comments" data-post-id="<%= @post.id %>">
    <%= render @post.comments %>
  </div>

</div>



<%= link_to 'Back', posts_path %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <p>This form has <%= pluralize(object.errors.count, 'problem') %></p>
  <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="#">Alumni App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link"><%= link_to "Home", root_path %> <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link"><%= link_to "Posts", posts_path %></a>
      </li>

      <% if signed_in? %>
        <li class="nav-item">
          <a class="nav-link disabled"> <%= link_to "Logout", destroy_user_session_path, method: :delete %></a>
        </li>
      <% else %>
        <li class="nav-item">
          <a class="nav-link disabled"> <%= link_to "Register", new_user_registration_path %></a>
        </li>
         <li class="nav-item">
          <a class="nav-link disabled"> <%= link_to "Login", new_user_session_path %></a>
        </li>
      <% end %>
    </ul>
    <form class="form-inline mt-2 mt-md-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>